# Generated by Django 2.2.3 on 2019-07-09 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='Anonymous', max_length=30)),
                ('avatar', models.ImageField(upload_to='./uploads/avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='./uploads/images/%Y')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='No title', max_length=100)),
                ('content', models.TextField()),
                ('file', models.FileField(upload_to='./uploads/markdown/%Y')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Author')),
            ],
        ),
    ]
